name: Frequent Auto Commit

on:
  schedule:
    - cron: '*/10 * * * *'  # 매 분마다 실행

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create changes
        run: |
          for i in {1..6}; do
            echo $(date) >> log.txt
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Auto commit $(date)"
            git push
            sleep 10
          done
      
      - name: Push final changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
